name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update
          sudo apt install python3-pip -y

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run script
        run: python3 analysis.py